name: B04

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, windows-latest, macos-latest]
        python-version: [3.7]
        project:
          - "project/rtos-blink"
          - "project/nonos-blink"
          - "project/arduino-blink"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          platformio platform install https://github.com/OS-Q/P04.git
      - name: Build B04
        run: |
          platformio run -d ${{ matrix.project }}
